### ISSUE TITLE
FreeBSD port for LPJS

### ISSUE THREAD

**Issue by sprock** [outpaddling/LPJS#1]
Hello,

I'm wondering if you would be willing to share your FreeBSD port for LPJS?

Also, I saw https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276001.  Did you manage to patch slurm-23.1.1 & get it working?  I tried and failed: socket programming is outside my experience and my C is very rusty.

Thanks,
sprock

**Comment by outpaddling** [comment]
The FreeBSD port is in outpaddling/freebsd-ports-wip, but it's far from ready for use.  When LPJS reaches a usable state, I will commit the FreeBSD port and pkgsrc package to the sysutils category.
Porting recent versions of SLURM would be a major uphill battle, as the developers have no interest in anything but Linux and continue to add more Linuxisms to new code.
